apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-watcher
  labels:
    component: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      component: watcher
  template:
    metadata:
      labels:
        component: watcher
    spec:
      containers:
      - name: container
        image: watcher
        command: ["./watcher/watcher",
                  "-metadata_service=metadata-grpc-service.kubeflow:8080",
                  "-resourcelist=watcher/dockerfiles/resource_list.json"]
